apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-analysis-agent
  namespace: use-case-cross-selling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-analysis-agent
  template:
    metadata:
      labels:
        app: stats-analysis-agent
    spec:
      containers:
      - name: stats-analysis-agent
        image: stats_analysis_agent:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          httpGet:
            port: 8000
            path: /health
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          httpGet:
            port: 8000
            path: /health
        env:
        - name: LITELLM_PROXY_API_KEY
          valueFrom:
            secretKeyRef:
              name: litellm-proxy-api-key-secret
              key: LITELLM_PROXY_API_KEY
        - name: LITELLM_PROXY_API_BASE
          value: "http://litellm.llm-gateway.svc.cluster.local:4000"
        - name: USE_LITELLM_PROXY
          value: "True"
        - name: OTEL_SERVICE_NAME
          value: stats-analysis-agent
        envFrom:
          - configMapRef:
              name: otel-tempo-config
              optional: true
          - configMapRef:
              name: agent-communications-dashboard-backend-config
              optional: true
