apiVersion: v1
kind: Service
metadata:
  name: stats-analysis-agent
  namespace: use-case-cross-selling
  labels:
    app: stats-analysis-agent
spec:
  selector:
    app: stats-analysis-agent
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
