apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: insurance-host-ragas-evaluation-trigger
  namespace: testkube
spec:
  resource: deployment
  resourceSelector:
    name: insurance-host-agent
    namespace: showcase-cross-selling
  event: modified
  action: run
  execution: testworkflow
  concurrencyPolicy: allow
  testSelector:
    name: insurance-host-ragas-evaluation
    namespace: testkube
  disabled: false