apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testkube
resources:
  - datasets.yaml
  - metrics.yaml
  - insurance-host-ragas-evaluation.yaml
  - insurance-host-ragas-evaluation-trigger.yaml
  - cross-selling-ragas-evaluation.yaml
  - cross-selling-ragas-evaluation-trigger.yaml
