apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - otel-tempo-config.yaml
  - agent-gateway.yaml
  - ai-gateway.yaml
  - otel-config-testkube.yaml
  - lgtm.yaml
  - lgtm-grafana-dashboard-config.yaml
