apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - customer-crm/
  - insurance-products/
  - communication-agent/
  - cross-selling-agent/
  - insurance-host-agent/
