apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: showcase-cross-selling
resources:
  - namespace.yaml
  - cross-selling-workforce.yaml
  - customer-crm.yaml
  - insurance-products.yaml
  - communications-agent.yaml
  - cross-selling-agent.yaml
  - insurance-host-agent.yaml
