apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-products
  namespace: showcase-cross-selling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-products
  template:
    metadata:
      labels:
        app: insurance-products
    spec:
      containers:
      - name: insurance-products
        image: insurance_products:latest
        ports:
        - containerPort: 8000
