apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-products
  namespace: showcase-cross-selling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-products
  template:
    metadata:
      labels:
        app: insurance-products
    spec:
      containers:
      - name: insurance-products
        image: insurance_products:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
