[project]
name = "insurance-products"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.1",
]

[project.scripts]
insurance_products = "insurance_products.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
