apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-crm
  namespace: showcase-cross-selling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-crm
  template:
    metadata:
      labels:
        app: customer-crm
    spec:
      containers:
      - name: customer-crm
        image: customer_crm:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
