apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-selling-agent
  namespace: use-case-cross-selling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cross-selling-agent
  template:
    metadata:
      labels:
        app: cross-selling-agent
    spec:
      containers:
      - name: cross-selling-agent
        image: europe-west3-docker.pkg.dev/qaware-paal/agentic-layer-private/cross_selling_agent:latest
        ports:
        - containerPort: 8000
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key-secrets
              key: GOOGLE_API_KEY
        - name: OTEL_SERVICE_NAME
          value: cross-selling-agent
        envFrom:
          - configMapRef:
              name: otel-tempo-config
              optional: true
