apiVersion: v1
kind: Service
metadata:
  name: cross-selling-agent
  namespace: use-case-cross-selling
  labels:
    app: cross-selling-agent
spec:
  selector:
    app: cross-selling-agent
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP