apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-host-agent
  namespace: use-case-cross-selling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-host-agent
  template:
    metadata:
      labels:
        app: insurance-host-agent
    spec:
      containers:
      - name: insurance-host-agent
        image: europe-west3-docker.pkg.dev/qaware-paal/agentic-layer-private/insurance_host_agent:latest
        ports:
        - containerPort: 8000
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key-secrets
              key: GOOGLE_API_KEY
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: OTEL_EXPORTER_OTLP_ENDPOINT
              name: otel-tempo-config
        - name: OTEL_SERVICE_NAME
          value: insurance-host-agent