apiVersion: v1
kind: Service
metadata:
  name: insurance-host-agent
  namespace: use-case-cross-selling
  labels:
    app: insurance-host-agent
spec:
  selector:
    app: insurance-host-agent
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
